### ISSUE TITLE
optional version without Node-RED

### ISSUE THREAD

**Issue by Misiu** [3ative/Smart-Candles#1]
Hi there,
your candles look awesome and very easy to do/implement. Thanks for sharing 👍
I'd like to ask for an alternative version without Node-RED. Is this even possible?

**Comment by 3ative** [comment]
Hi @Misiu,
Thanks for the feedback - Glad you liked it.

The main reason I use Node-Red for my devices is for the Alexa control (See my other video for more)
However, as they both do [pretty much] the same thing, I can't see it being too hard to do 'native-ly' with something like an automation or scrips.
I'll look in to it asap

**Comment by Misiu** [comment]
@3ative thanks for such a fast reply.
The reason I asked for an alternative version without Node-RED is quite simple: I think not everyone (including me) is using it. I run HA on Raspberry Pi 3B (not the plus version), so I want to avoid adding extra things to don't slow it down.

One additional question:
I saw that you define that input in a separate file. How did you configure HA to read from that file? https://www.home-assistant.io/docs/configuration/splitting_configuration/#advanced-usage there are multiple options. Which one did you use?

**Comment by 3ative** [comment]
I've not seen that link :)

I've split my config up in to files and folders - I got the idea from one of Frenks streams. 

I does make organising and finding stuff easier, it's not necessary as you can simply add the slider in to your main configuration.yaml like this:

```yaml
input_number:
  candles:
    name: Candles
    initial: 0
    min: 0
    max: 100
    step: 10
    mode: slider
```

More options here: https://www.home-assistant.io/integrations/input_number/

**Comment by Misiu** [comment]
@3ative I'm aware it's optional, but it makes life easier. That's what I want to do, but I don't know which option to pick: `!include_dir_merge_list`? It's somewhere in configuration.yaml.

**Comment by 3ative** [comment]
See if this helps...

I've got all the folders in a main folder called "_setup" - I use the underscore so its at the top of the file list. 
Then in config yaml I have these:

```yaml
automation: !include_dir_merge_list _setup/automations
climate: !include_dir_merge_list _setup/climate
device_tracker: !include_dir_merge_list _setup/device_tracker
group: !include_dir_merge_named _setup/groups
input_boolean: !include_dir_merge_named _setup/input_boolean
input_number: !include_dir_merge_named _setup/input_number
light: !include_dir_merge_list _setup/lights
recorder: !include_dir_merge_named _setup/recorder
rest_command: !include_dir_named _setup/rest_command/
script: !include_dir_merge_named _setup/scripts
sensor: !include_dir_merge_list _setup/sensors
shell_command: !include_dir_merge_named _setup/shell_command
switch: !include_dir_merge_list _setup/switches
```
I must admit, it was a bit of hit & miss whether each one need; "**!include_dir_merge_list**" or "**!include_dir_merge_named**". But, if you follow mine you should be ok.

**Comment by Misiu** [comment]
@3ative I will follow your setup :)

**Comment by 3ative** [comment]
@Misiu 
Ok, I figured it out  😎 - You CAN do it with just an automation.
Here's how:
```yaml
- alias: candle_tester
  trigger:
    platform: state
    entity_id: input_number.candles

  action:
    - service: light.turn_on
      data_template:
        entity_id:
          - light.candle_1
          - light.candle_2
        brightness_pct: "{{trigger.to_state.state}}"
        transition: 1
        effect: flicker
```
